services:
  hypervel_v2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hypervel_v2
    ports:
      - "9501:9501"
    volumes:
      - .:/data/project
    privileged: true
    user: "0:0"
    stdin_open: true
    tty: true
    security_opt:
      - seccomp:unconfined
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_hypervel
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hypervel_db
      MYSQL_USER: hypervel_user
      MYSQL_PASSWORD: hypervel_password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_hypervel
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_USER: hypervel_user
      PMA_PASSWORD: hypervel_password
    depends_on:
      - db

volumes:
  db_data:
